src/en/ref/Constraints/url.gdoc
src/es/ref/Constraints/url.gdoc
src/fr/ref/Constraints/url.gdoc
src/th/ref/Constraints/url.gdoc
src/zh_CN/ref/Constraints/url.gdoc
src/zh_TW/ref/Constraints/url.gdoc

`UrlConstraint` uses its own `UrlValidator` and `DomainValidator`, and does *not* use `commons-validator`.  This matters when trying to get Grails to accept new TLDs, such as `.pizza` or `.wtf`: upgrading `commons-validator` to the latest version won't help, no matter how hard you try, since it is not used to validate URLs, and the Grails `DomainValidator` class maintains its own TLD list.
OTOH, `EmailConstraint` and `CreditCardConstraint` *do* use the corresponding `commons-validator` classes.

Fix incorrect doc on `UrlConstraint` using `commons-validator`.

---

src/en/guide/conf/dataSource.gdoc

A minor mistake in sentence in Datasource documentation.

Fix missing with in Datasource documentation

---

src/en/guide/GORM/advancedGORMFeatures/ormdsl/caching.gdoc

Docs still refer to `DataSource.groovy`

fix docs for hibernate second-level cache

---

src/en/ref/Tags/formatDate.gdoc

formatDate tag has a wrong link to TimeZone class api doc.

Fixing problem with TimeZone link in formatDate tag

---

src/en/guide/conf/dataSource/multipleDatasources.gdoc
src/en/guide/hibernate/mappingWithHibernateAnnotations.gdoc
src/en/guide/hibernate/usingHibernateXMLMappingFiles.gdoc
src/es/guide/hibernate/mappingWithHibernateAnnotations.gdoc
src/es/guide/hibernate/usingHibernateXMLMappingFiles.gdoc
src/es/ref/Command Line/create-hibernate-cfg-xml.gdoc
src/fr/guide/hibernate/mappingWithHibernateAnnotations.gdoc
src/fr/guide/hibernate/usingHibernateXMLMappingFiles.gdoc
src/fr/ref/Command Line/create-hibernate-cfg-xml.gdoc
src/pt_PT/guide/hibernate/mappingWithHibernateAnnotations.gdoc
src/pt_PT/guide/hibernate/usingHibernateXMLMappingFiles.gdoc
src/pt_PT/ref/Command Line/create-hibernate-cfg-xml.gdoc
src/th/guide/hibernate/mappingWithHibernateAnnotations.gdoc
src/th/guide/hibernate/usingHibernateXMLMappingFiles.gdoc
src/th/ref/Command Line/create-hibernate-cfg-xml.gdoc
src/zh_CN/guide/hibernate/mappingWithHibernateAnnotations.gdoc
src/zh_CN/guide/hibernate/usingHibernateXMLMappingFiles.gdoc
src/zh_CN/ref/Command Line/create-hibernate-cfg-xml.gdoc
src/zh_TW/guide/hibernate/mappingWithHibernateAnnotations.gdoc
src/zh_TW/guide/hibernate/usingHibernateXMLMappingFiles.gdoc
src/zh_TW/ref/Command Line/create-hibernate-cfg-xml.gdoc

Updated the path for hibernate.cfg.xml from grails-app/conf/hibernate to grails-app/conf as the old path does not take effect in Grails 3.0.1. For a more detailed description of the issue refer to: http://stackoverflow.com/questions/30830155/mapping-with-hibernate-annotations-in-grails-3-0-1

Updated the path for hibernate.cfg.xml to grails-app/conf

---

src/en/guide/theWebLayer/interceptors/interceptorMatching.gdoc

"cannot be used in combination with other arguments" was not clear about what would happen in case it is used together. Added the details for that.

Matching Requests with Inteceptors - Made uri details more precise

---

src/en/guide/theWebLayer/interceptors/interceptorMatching.gdoc

Looked through the Interceptor traits source code and found that any number of matchers can be defined. Added the missing information to the documentation.

Interceptor - Added details for multiple matchers

---

src/en/guide/toc.yml
src/en/guide/traits/traitsprovided.gdoc

https://grails.github.io/grails-doc/latest/guide/traits.html had two headings. Fix for that.

Fix for two heading in traits documentation

---

src/en/guide/theWebLayer/contentNegotiation.gdoc

Fix for Config.groovy being replaced in the section "Content negotitation"

Fix for Config.groovy being replaced in the section "Content negotitation"

---

src/en/guide/conf/config/ymlOptions.gdoc
src/en/guide/toc.yml

Added the information shared in https://github.com/grails/grails-core/issues/9086#issuecomment-119301515

Added information regarding yml format.

---

src/en/guide/contributing/patchesCore.gdoc

If not you risk being out of sync with upstream master forever. Also, if you add more changes to master they will all be part of the same Pull Request.

Send Pull Request from branch, not from master.

---

build.gradle
gradle.properties
src/en/guide/contributing/patchesDoc.gdoc

Fix https://github.com/grails/grails-doc/issues/339

Fix for grails.home set to not cause source to be fetched

---

src/en/guide/testing/unitTesting/unitTestingControllers.gdoc
src/en/guide/testing/unitTesting/unitTestingFilters.gdoc
src/en/guide/testing/unitTesting/unitTestingTagLibraries.gdoc
src/en/guide/testing/unitTesting/unitTestingURLMappings.gdoc

Added a few missing imports for Mock and TestFor to examples of the
testing guide.

Fix imports in test examples

---

src/en/guide/GORM/querying/whereQueries.gdoc
src/en/ref/Command Line/create-hibernate-cfg-xml.gdoc

missing Advanced subqueries content section from Gorm grails doc 2.5.0 content has been added to latest GORM documentation as per https://github.com/grails/grails-doc/issues/266 this issue opened.

Advanced subqueries content section from Gorm grails doc 2.5.0 content has been added to latest GORM documentation

---

src/en/guide/upgradingFromPreviousVersionsOfGrails.gdoc

The documentation refers to ehcache 2.4.6, which is very much out of date. Refer to the latest version (which as of right now is 2.8.1) instead.

Tell users to use the latest verison of ehcache

---

src/en/guide/webServices/REST/hypermedia/hal.gdoc

In the "Customizing Link Rendering" section of "HAL Support", the example code doesn't produce the resulting output shown below.

custom link should be created with createLink instead of link

---

src/en/ref/Controllers/flash.gdoc

Added "be" to "can be retrieved".
Removed space before closing parenthesis (had to use another syntax for the link).

Fix typo and formatting in flash.gdoc

---

resources/doc.properties

Changed `api.grails.` to `http://grails.github.io/grails-data-mapping/latest/api`. Issue number #357 can now be closed.

Corrected the url for orm docs. Resolving issue #357.

---

gradle.properties

Issue #351 is now resolved and can be closed. We don't need any script and all, as the Grails version is controlled by the value `grails.version` in the file `gradle.properties` I've changed it to 3.0.4 and checked if version is correct in generated docs. It's safe to merge this commit with master.

Updated docs to use grails version 3.0.4. Resolving issue #351.

---

src/en/ref/Tags/form.gdoc

Added description for attribute "method" of tag "form" to the reference
documentation. The description is based on API documentation.

Add form method description

---

resources/doc.properties

Should be grails-doc instead of grails-data-mapping

Fix broken links to api docs

---

gradle.properties
src/en/guide/testing.gdoc
src/en/ref/Command Line/test-app.gdoc

Updated test-app command documentation to show Grails 3 syntax for running integration or unit tests.
Updated testing guide to add switch to target failed tests.

Update test app docs

---

src/en/guide/upgrading.gdoc

Trivial Fix for the upgrading.gdoc page.  The File Location Differences header was duplicated on the page when it should only be listed once.

Deleted Duplicate File Differences Header in Upgrading Gdoc

---

build.gradle
src/en/ref/Tags/fieldError.gdoc
src/en/ref/Tags/include.gdoc
src/en/ref/Tags/paginate.gdoc
src/en/ref/Tags/sortableColumn.gdoc

Related to grails/grails-core#9323, if that is accepted the other change will be to update the `grails-doc` dependency in the `build.gradle` file.

Issue #9090 - Grails docs not building the source tags

---

src/en/guide/security/xssPrevention.gdoc

Since application.yml is the new default configuration format, I changed the filename and the config example to match.

[CORRECTED]Update Default XSSPrevention to YAML Format

---

src/en/ref/Domain Classes/hasErrors.gdoc
src/en/ref/Domain Classes/save.gdoc
src/en/ref/Domain Classes/validate.gdoc

All occurrences of `errors.each` changed to `errors.allErrors.each`,
because the former is incorrect, i.e. does not iterate over errors.

Fix examples with errors.each (fix #360)

---

src/en/guide/upgrading/upgrading2x/upgradingPlugins.gdoc

Implements issue #9416.
The way that the `pluginExcludes` property works in plugin descriptors
has changed with Grails 3. This adds an extra documented upgrade step
explaining what changes a developer needs to make to an old Grails 2.x
plugin.

Add `pluginExcludes` to migration instructions.

---

src/en/ref/Command Line.gdoc

Grails won't search in `PROJECT_HOME/scripts/`.
It will search in `PROJECT_HOME/src/main/scripts/`.
At least it's how it worked for me.

Update Command Line.gdoc

---

src/en/guide/testing.gdoc

We've experienced that the -rerun command no longer exists in Grails 3, and think it would be helpful to those looking up testing commands to have the debug instructions made easily available. 
Please let me know how to better phrase / polish these additions and I will happily oblige!

Improving Testing Documentation

---

src/en/guide/async.gdoc
src/en/guide/scaffolding.gdoc
src/en/guide/theWebLayer/controllers/commandObjects.gdoc
src/en/guide/webServices/REST/domainResources.gdoc
src/en/guide/webServices/REST/hypermedia/hal.gdoc
src/en/guide/webServices/REST/hypermedia/vndError.gdoc
src/en/guide/webServices/REST/versioningResources.gdoc

There are still a number of examples with context-paths.  
```
http://localhost:8080/myapp/books/1  --->  http://localhost:8080/books/1
```

Remove remaining context-paths from example URLs, fix stale link

---

src/en/guide/plugins/providingBasicArtefacts.gdoc

Fixes UrlMappings path, see #415

#415 fix UrlMappings example path - Update providingBasicArtefacts.gdoc 

---

src/en/ref/Domain Classes/createCriteria.gdoc

It can very difficult to figure out where the criterion methods are. Copy-pasting the examples on this page leads to a lot of syntax errors.

Added text that describes where to get the criterion methods

---

src/en/guide/gettingStarted/ide.gdoc

Fixing a typo in the IDE setup section in Getting Started.

Fix typo choise -> choice

---

src/en/ref/Command Line/schema-export.gdoc

After severely missing `grails schema-export` in Grails 3, I found the solution [here](https://groups.google.com/forum/#!topic/grails-dev-discuss/V-tyaJhwmuA).
I figured I would update the docs.

Adding Grails 3 clarification on adding Hibernate to build classpath for grails schema-export 

---

src/en/guide/testing/functionalTesting.gdoc

As of Grails 3.1.9 the default port used in a test with @Integration is
random and can be found at serverPort.

Add serverPort documentation

---

src/en/guide/upgrading/upgrading3x.gdoc

After some research with the filters plugin support in Grails 3.1 and checking it also in the Slack chat, @burtbeckwith gave me some light and told me that filters shouldn't be in grails-app/conf folder as it is not considered a source folder anymore so we should move the filters to any other source folder, probably recommended grails-app/controllers

Updating filters documentation when upgrading application to Grails 3.1

---

src/en/guide/testing/integrationTesting.gdoc

As of v3.0.10, the transactional behavior of integration tests is different than that presented in the [documentation](http://docs.grails.org/latest/guide/testing.html#integrationTesting). Commit [cc2f2ed86d18fded831242d0c8d2d1ee885fc8a5 in grails-core](https://github.com/grails/grails-core/commit/cc2f2ed86d18fded831242d0c8d2d1ee885fc8a5#diff-f87e8a1222b58264b3d2056e39fb6086) introduced the ability to persist objects in the `setup()` method of integration tests via the default `@Rollback` annotation.
That commit essentially wrapped the contents of the `setup()` method in its own transaction that is not rolled back.
This change applies to the 3.1.x and 3.2.x lines as well, I can make a pull request to a different branch if that's more appropriate.

Update integration test documentation for transaction changes

---

src/en/guide/theWebLayer/controllers/uploadingFiles.gdoc

Hi @graemerocher and @jeffbrown 
This is related to #489
Includes upload maxFileSize and maxRequestSize documentation
As suggested by Graeme in https://github.com/grails/grails-doc/pull/491#issuecomment-246262396 I opened a pull request to add this to the `3.0.x` branch and make this change available for Grails 3.x

Include upload maxFileSize and maxRequestSize. 

---

src/en/ref/Command Line/create-app.adoc

Opening against 3.0.x as I think that's how things get merged up? I honestly forget each time.

--skip-wrapper does not exist in grails 3

---

src/en/ref/Tags/meta.adoc

When I change the info.app.grailsVersion I do it in the gradle.properties file called grailsVersion and the info.app.version in the build.gradle file called version.  I do not see them in the application.yml file.

meta properties in other files

---

src/en/guide/testing/unitTesting/unitTestingDomains.adoc

Some list items are using`#` instead of `*` and appear as titles

Turn accidental titles into list items

---

src/en/guide/webServices/REST/binding.adoc

The table is specified in a CSV format. The intended content of the cells in column 1, rows 1 and 2 was not enclosed in quotes and contained commas. This caused the content to be rendered in separate cells meaning the rest of the content was shifted across by one or two cells, with the last two cells missing completely.

Fix the rendering of DataBindingSourceCreator implementation table

---

src/en/guide/webServices/REST/hypermedia/hal.adoc

I followed the instructions on with rendering responses in the HAL format but kept on getting a 406 response from the server. I eventually figured out I needed to added HAL to the list of acceptable responses. This information was missing from the documentation so I created this proposed change.

Info on adding HAL as an acceptable response format

---

src/en/guide/upgrading/upgrading31x.adoc

Using default namespace will break applications in a sneaky manner only after being deployed to staging/production and should be mentioned in the upgrade docs.

Document abolishing the default namespace as an upgrade step

---

src/en/guide/upgrading.adoc

Since the table using csv format, the comma in "(yes, groovy!)" made the following table cells content messy.
Unable to get it escaped after an hour of searching and trying, I change it to traditional format table.

The comma in the CSV format table

---

src/en/guide/gettingStarted/downloadingAndInstalling.adoc

The changes may sound obvious, but it helps those that never used SDKMAN and just wants to install Grails without going back and forth on SDKMAN docs.

improving installation using SDKMAN docs

---

travis-build.sh

The documentation for 3.1.x Shouldn't be published as `latest`

Disable publishing of /latest/ for 3.1.x documentation

---

src/en/guide/testing.adoc

In Grails 3.2.4, for example, to run a specific test, you need to do:
```
grails test-app com.yourcompany.yourapp.ProductControllerSpec
```
In order to run a specific test for, as an example, the ProductController.
Note you need the word **Spec** appended to the end of the class name as well as the specification of the package hierarchy.

Add note about Grails 3.x's usage of test-app

---

src/en/guide/testing.adoc

For Grails 3.2.4, when you create a controller using create-controller, a test is created in the following directory:
```
Created src/test/groovy/com/yourcompany/yourapp/ProductControllerSpec.groovy
```
The example above uses com.yourcompany.yourapp.ProductController as an example. So in general, the path is  **src/test/groovy/something/SomethingSpec.groovy**

Update unit test directory in Testing documentation introduction

---

src/en/ref/Constraints.adoc

Use the standard AsciiDoc table syntax to fix issues caused by using the CSV syntax.

Fix table formatting on Constraints Usage page

---

src/en/ref/Tags/fieldValue.adoc

The optional valueMessagePrefix was added & merged to the fieldValue tag in grails/grails-core#10527

Add valueMessagePrefix to fieldValue.adoc

---

src/en/ref/Tags/form.adoc

Added a # per the ascii doctor documentation:
See the <<README#,README>>.
http://asciidoctor.org/docs/user-manual/#navigating-between-source-files

Link to form token now working

---

src/en/ref/Tags/link.adoc

Just a small change to make things clearer, it seems that in the documentation as it stands that the roles of id and elementId are reversed.  See http://stackoverflow.com/questions/43754126/how-do-i-pass-an-id-to-a-link-when-using-the-method-call-syntax-in-a-taglib/43775473#43775473

elementId vs id confusion

---

src/en/ref/Tags/createLink.adoc

I had to find this obvious syntactical difference while using <g:createLink vs <a tag. What I am referring to is, '=' needs to be replaced with ':' and needs proper quotes. It might be obvious, but not for novice like me.

Adding a subtle but important syntax

---

src/en/guide/testing/functionalTesting.adoc

Since Grails 3.x, a functional test is a kind of a integration test in the view point of test phase. So there is no such difference.

Fix about differences between fuctional and integration

---

src/en/ref/Tags/select.adoc

added a documentation-section, as the select-syntax changed from grails v2.5.5 and the only hint was the response to this issue:
https://github.com/grails/grails-core/issues/9347

updated doc for select from constraints of domain

---

src/en/guide/upgrading.adoc

All api links in http://docs.grails.org/latest/guide/upgrading.html are rendered as ` http://docs.grails.org/latest/guide/%7Bgormapi%7D/org/grails/datastore/mapping/model/MappingContext.html`.

Fix upgrading api links

---

src/en/guide/services/dependencyInjectionServices.adoc

Services are not injected by default in domains anymore, so this doc should be changed in order to explain new behaviour

Update doc: Services not injected in domains

---

src/en/guide/commandLine/creatingCustomCommands.adoc

Add note about the return value for the `handle` method in both `ApplicationCommand` and `GrailsApplicationCommand`, indicating that successful command execution should return true, and false otherwise.

Add note about return value for `handle`

---

src/en/guide/plugins/repositories.adoc

I think new url is https://grails.org/plugins/

wrong url plugin portal website

---

src/en/guide/theWebLayer/controllers/commandObjects.adoc

It looks like the items are intended to be rendered as a bulleted list but do not use the necessary markup.

Render list in note about parsing request body.

---

src/en/guide/i18n/readingMessages.adoc

Following the separation of the GSP documentation from the Grails documentation, the link to the documentation for the Message Tag is broken...

Fix broken link to GSP documentation

---

src/en/ref/Tags/each.adoc

Attributes on page "Tags" are too big. According to another pages it shouldn't be so big.

3.2.x Resizing the topics on "Attributes" section for "Tags" page

---

src/en/guide/profiles/profileStructure.adoc

The trick is to use `*` as version

Dependency exclusions need to indicate a version

---

src/en/ref/Domain Classes/save.adoc

Updated documentation of the save(flush: true) behaviour description inside transactions

Updated save.adoc - flush description for transactions

---

src/en/guide/conf/config.adoc

`runtime.groovy` was introduced in Grails 3.2 in response to https://github.com/grails/grails-core/issues/10131 but was only documented in the upgrade notes, and has therefore disappeared from the latest version of the documentation.
The existence of `runtime.groovy` and the reason why it is required should be documented in the Configuration chapter.

Add documentation for runtime.groovy

---

src/en/guide/theWebLayer/urlmappings/restfulMappings.adoc

According to deprecation warning the `resource` property is being replaced with `single` for what i assume is clarity.

Updated single resource property to single

---

src/en/ref/Command Line/run-app.adoc

Included an example of how to use the -port argument when using run-app from the command line.

Include example of using -port

---

src/en/guide/plugins/creatingAndInstallingPlugins.adoc

Ie. documented that create-plugin utilizes the web-plugin profile by default.
(Current behavior in Grails v3.3.5)

Clarified default behavior for create-plugin

---

src/en/guide/testing/unitTesting.adoc

grails-test-mixins 3.3.0.RC1 -> 3.3.0

---

src/en/guide/gettingStarted/requirements.adoc

For JMX connector features to work (such as stop-app) the JAVA_HOME environment variable must be set, so include that wording.
Addresses the cause of https://github.com/grails/grails-core/issues/11119, which can be confusing to someone just encountering it.

Improve wording regarding JAVA_HOME requirements

---

src/en/guide/conf/dataSource/multipleDatasources.adoc

Remove repeated 'by default' from multipleDatasources.adoc
Somehow github is showing a difference on line 288 as well, nothing changed there.

Remove repeated 'by default'

---

src/en/ref/Controllers/render.adoc

Render with status code + text suggests a use of string interpolation in the text string. It can not be done in a plain Java String defined with simple quotes: use double quotes instead

render.adoc: Use double quotes for GString

---

src/en/guide/conf/config/configGORM.adoc

autoFlush is deprecated according to http://gorm.grails.org/snapshot/mongodb/api/org/grails/datastore/mapping/core/connections/ConnectionSourceSettings.html#autoFlush

Remove autoFlush

---

src/en/ref/Controllers/header.adoc

The `header` method is a way to add response headers from Controller methods; this should document it.

Add header method to Controller in quick reference 

---

src/en/guide/profiles/profileInheritance.adoc

Custom plugins generally won't be built as part of a multiproject build along with `base`, `plugin` and `web`.

Update Gradle Samples

---

src/en/guide/gettingStarted/deployingAnApplication.adoc

Since Grails 4 requires a JDK 8 as per https://docs.grails.org/4.0.0/guide/single.html#requirements the PermGen space-related `XX:MaxPermSize` is obsolete.

Remove obsolete JVM parameter

---

src/en/guide/commandLine/gradleBuild.adoc

Updated reference to Grails 3.1 to Grails 3.1 (and higher).

Updated reference to Grails 3.1

---

src/en/guide/introduction/whatsNew/dependencyUpgrades.adoc

- Grails version was not updated since 4.0.7.

Use version placeholder in dependencyUpgrades.adoc (4.0.x branch)

---

src/en/ref/Constraints/maxSize.adoc

`minSize` clearly states that it can be used for collections, but `maxSize` does not mention anything specifically.
Updated to aid in clarity

Clarify maxSize usage

---

src/en/ref/Constraints/email.adoc

We encountered this new behavior today in a system that was upgraded from Grails 3.2.3 to Grails 4.0.12.
Relevant Code:
```
package org.grails.datastore.gorm.validation.constraints;
import grails.gorm.validation.ConstrainedProperty;
import org.apache.commons.validator.routines.EmailValidator;
import org.springframework.context.MessageSource;
import org.springframework.util.StringUtils;
import org.springframework.validation.Errors;
/**
* Validates an email address.
*
* @author Graeme Rocher
* @since 0.4
*/
public class EmailConstraint extends AbstractConstraint {
```

Update email.adoc to reflect new email validator

---

src/en/guide/upgrading.adoc

Must Set gradle.properties before calling ./gradlew
...or else:
> Failed to apply plugin [class 'org.springframework.boot.gradle.plugin.SpringBootPlugin']
> Spring Boot plugin requires Gradle 4.4 or later. The current version is Gradle 3.5

Set gradle.properties before calling ./gradlew

---

src/en/guide/plugins/creatingAndInstallingPlugins.adoc
src/en/guide/upgrading/upgrading40x.adoc

relates to https://github.com/grails/grails-core/issues/12367
* upgrade section guide related to full removal of compile configuration name in Gradle 7 as well as the impact on grails plugins in multi-project builds
*  updates to snippets where `implementation` configuration needs to be used as compile is not available any more

Information about to Gradle 7 upgrade required changes

---

src/en/guide/gettingStarted/deployingAnApplication.adoc

Update the getting started documentation about `spring-boot-starter-tomcat` so it is current for Grails 5 and consistent with this guide:
https://github.com/grails/grails-doc/blob/0d2248cea237ef5281edc26f2e5322750dc9608e/src/en/guide/deployment/deploymentContainer.adoc

Update the documentation about spring-boot-starter-tomcat

---

src/en/guide/conf/config/logging.adoc
src/en/guide/conf/config/logging/externalLoggingConfiguration.adoc
src/en/guide/upgrading/upgrading40x.adoc

Remove documentation of logback.groovy from the logging section.
According to https://logback.qos.ch/news.html logback.groovy support was removed to mitigate [CVE-2021-42550](https://cve.report/CVE-2021-42550). See also https://jira.qos.ch/browse/LOGBACK-1591.

Remove logback.groovy from documentation

---

src/en/guide/testing/unitTesting.adoc

Cleans up testing documentation which states that the test mixin framework is still usable

Cleans up testing documentation which states that the test mixin framework is still usable

---

src/en/guide/deployment/deploymentContainer.adoc

http://grails.org/Deployment
Should be replaced by I presume: https://docs.grails.org/latest/guide/single.html#supportedJavaEEContainers

Update the link "Deployment"

---

.github/actions/tag-and-release/entrypoint.sh

Append "[skip ci]" to commit message to skip trigger Java CI workflow for release commit.

Update Action TagAndRelease

---

src/en/guide/introduction/whatsNew.adoc

This version of the text:
- Removes the mention of Spring Framework 5.3 and Groovy 3, as these were already the versions used in Grails 5.
- Does not show the patch release version of Spring Boot 2.7.12, as this is not relevant to the overall message.
- Corrects the misconception that Groovy 3 requires Java 11.

Clarify the overview in the What's new section.

---

src/en/guide/introduction/whatsNew.adoc

after installing grails 5.3.3 and run ./gradlew dependencies the out put is: org.springframework.boot:spring-boot:2.7.9 -> 2.7.8 , org.codehaus.groovy:groovy:3.0.11

fix dependencies in whatsNew.adoc

---

src/en/guide/gettingStarted/requirements.adoc

Addresses issue #772 to aid those new to Grails to get going with the correct SDK.

Update doc in order to specify an upper JDK limit.

---

.github/workflows/gradle.yml
.github/workflows/release.yml

Snapshots for the active branch were not published because of a condition in the github workflow.
The SKIP_SNAPSHOT env var should suffice to prevent snapshot publishing of older branches.
Also formatted the SKIP_SNAPSHOT conditions, so it is easier to read and maintain, especially when more branches are added.

fix(ci): Update snapshot publishing

---

src/en/ref/Dependency Versions/Grails BOM.adoc

Add `org.mongodb:bson` and `org.mongodb:bson-record-codec` to the BOM details page.

docs: Update Grails BOM.adoc

---

src/en/ref/Dependency Versions/Grails BOM.adoc

For readability, this commit sorts the BOM table rows by groupId/artifactId and artifactId cells alphabetically.

fix(docs): Sort BOM entries

---

.github/workflows/gradle.yml
build.gradle
src/en/guide/toc.yml
src/en/guide/upgrading/upgrading60x.adoc

This commit starts updating the docs to Grails 7 by adding an upgrade guide. Dependency versions are not yet known and are set as X.X.X.
Added section on breaking changes, in particular the problem with inheritance in GORM.

New section: Upgrading to 7 and breaking changes
