grails/grails-doc

src/en/guide/webServices/REST/versioningResources.gdoc
Otherwise you will receive Response code: 406 Response message: Not Acceptable
=> responseFormats needs to be updated

src/en/guide/webServices/REST/hypermedia/hal.gdoc
Considered raising a Jira for this as I am not sure this is the best place for this note.  The "Versioning REST resources" section might benefit from further expansion or, can we just reference another persons' work, e.g. http://barelyenough.org/blog/2008/05/versioning-rest-web-services/.  I guess we do not want to full the grails manual with everything about web services.  I was worried that the examples are not representative of actual practice.
=> Qualify use of media-range

src/en/guide/gettingStarted/aHelloWorldExample.gdoc
using contextPath instead of context-path
=> #264 updated doc to reflect grails-core change grails-9020

src/en/guide/webServices/REST/hypermedia.gdoc
=> Fixed small typo

src/en/guide/conf/docengine.gdoc, src/es/guide/conf/docengine.gdoc, src/fr/guide/conf/docengine.gdoc, src/pt_PT/guide/conf/docengine.gdoc, src/th/guide/conf/docengine.gdoc, src/zh_CN/guide/conf/docengine.gdoc, src/zh_TW/guide/conf/docengine.gdoc
Replaced invalid link http://textile.sitemonks.com/ with valid Textile Markup hyperlink
=> The Textile hyperlink is broken and needs to be updated

src/en/guide/theWebLayer/interceptors/definingInterceptors.gdoc
Fixed sentence as earlier one was having problem 
The code looked like it had been copy pasted from Interceptor. That was looking odd as per indentation.
=> Changes in "Defining Interceptors" for clarity

src/en/guide/testing/functionalTesting.gdoc
=> Making indent length consistent

src/en/ref/Tags/pageProperty.gdoc
Took examples from one of my personal projects and added attribute details from the source code of grails 3.0.2
https://github.com/grails/grails-doc/issues/252
=> g:pageProperty documentation improvement

src/en/ref/Tags/fieldValue.gdoc
PR for https://github.com/grails/grails-doc/issues/262
=> fieldValue tag return value - Added clarity

src/en/guide/theWebLayer/interceptors.gdoc
I checked the plugin and @CompileStatic is being used in the files.
=> Interceptors - Changed "can using CompileStatic" to "can use CompileStatic"

src/en/guide/upgrading.gdoc, src/en/guide/upgrading/upgradingApps.gdoc
Pull request for https://github.com/grails/grails-doc/issues/271
=> Pull request for #271

src/en/guide/theWebLayer/urlmappings/restfulMappings.gdoc
Recently came to know the command `url-mappings-report`. This can be really helpful for restful controllers where the mapping is happening dynamically as per HTTP methods.
=> Added about the command url-mappings-report

src/en/guide/theWebLayer/contentNegotiation.gdoc
Content Negotiation with the format Request Parameter was present in two places. Merged their contents
=> Merged duplicate documentation

src/en/guide/conf/docengine.gdoc, src/en/ref/Command Line/docs.gdoc
https://github.com/grails/grails-core/issues/9067#issuecomment-117494109
=> Updated documentation for doc command

src/en/ref/Command Line/stop-app
Docs for stop-app added in https://github.com/grails/grails-core/issues/641
=> Added stop-app documentation

src/en/ref/Command Line/list-plugins.gdoc
=> Removed incorrect information for list-plugins

src/en/guide/contributing/issues.gdoc, src/en/guide/toc.yml
=> Updated contributing documentation for issues

src/en/guide/commandLine/creatingCustomScripts.gdoc
Same was present under "Defining Profile Commands"
=> The same line was present in the above paragraph of profiles also

src/en/ref/Plug-ins/logging.gdoc
For https://github.com/grails/grails-doc/issues/274
=> Changed log4j to logback

src/en/guide/contributing/patchesDoc.gdoc
https://github.com/grails/grails-doc/issues/310
=> Removed info about public fork as that is not used

src/en/guide/testing/functionalTesting.gdoc
As per the path in https://github.com/grails3-plugins/geb/blob/master/src/main/scripts/CreateFunctionalTest.groovy
=> Corrected path

src/en/guide/plugins/creatingAndInstallingPlugins.gdoc
As per https://github.com/grails/grails-profile-repository/blob/master/profiles/base/commands/plugin-info.groovy
Related https://github.com/grails/grails-doc/issues/317
=> Updated docs for plugin descriptor

src/en/guide/conf/config/ymlOptions.gdoc
As per comments in https://github.com/grails/grails-doc/pull/313
=> Grammar mistake

src/en/guide/services/dependencyInjectionServices.gdoc
https://github.com/grails/grails-core/issues/9091
=> Added top level only injection note

src/en/guide/testing.gdoc
Refactored outdated parts to reflect how unit and integration phases are handled in grails3.
Closes #305
=> Updated outdated testing phase/type chapter

src/en/guide/contributing/issues.gdoc
Fixed grammar, content.
@graemerocher Is the part regarding "Reviewing issues" needed?
=> Grammar, content in contributing

src/en/guide/theWebLayer/controllers/dataBinding.gdoc
This may catch people off guard so good to have it as a note.
=> Made a note about the limit

src/en/guide/contributing/build.gdoc
Seems really useful as gvm can be really handy.
=> Added information to use via gvm

src/en/guide/contributing/patchesCore.gdoc
=> Use GitHub issue id rather than Jira id

src/en/guide/webServices/REST/binding.gdoc
There is the same content at just below.
=> remove duplicate content

src/en/guide/upgrading/upgradingApps.gdoc, src/en/guide/upgrading/upgradingPlugins.gdoc
as discussed in https://github.com/grails/grails-doc/pull/346#issuecomment-125783341
=> removed * form copy commands im migration section

src/en/ref/Tags/fieldError.gdoc
Issue https://github.com/grails/grails-doc/issues/281 missing fieldError tag documentation has been added.
=> fieldError document added to grils docs

src/en/guide/conf/config.gdoc, src/en/guide/conf/dataSource.gdoc, src/en/guide/conf/dataSource/databaseConsole.gdoc, src/en/guide/conf/dataSource/multipleDatasources.gdoc, src/en/guide/conf/environments.gdoc
Fixed a few typos, formatting issues, etc.
=> Fix minor issues in conf guide

src/en/guide/theWebLayer/gsp/layouts.gdoc, src/en/ref/Tags/layoutTitle.gdoc, src/en/ref/Tags/pageProperty.gdoc
Fixed messed up tags and multiple formatting issues.
=> Fix layout examples

src/en/guide/theWebLayer/controllers/dataBinding.gdoc
Add the bindable constraint to the list of methods to secure data binding
=> Add bindable constraint to the data binding security section

src/en/guide/theWebLayer/gsp/resources.gdoc
Another possibility, where to put static resources, described.
=> resources.gdoc

src/en/guide/async/promises.gdoc
For https://github.com/grails/grails-core/issues/9356
=> Added ReactorPromiseFactory in docs

src/en/guide/theWebLayer/urlmappings/mappingToControllersAndActions.gdoc
=> Adds support for nested group url mappings

src/en/guide/conf/config.gdoc
Added a paragraph/code sample illustrating use of config.getProperty() while supplying a type and/or default values.
=> Added description of using config.getProperty() with type, default values

src/en/guide/contributing/build.gdoc, src/en/guide/gettingStarted/runningAndDebuggingAnApplication.gdoc, src/en/guide/links.yml, src/en/guide/toc.yml
I have added some information on how to do debugging. Not sure If I was supposed to change the `links.yml` file since the docs don't talk about it, but the generated documentation seems to work fine.
also relates to https://github.com/grails/grails-core/issues/9213
=> Debugging grails app

build.gradle, src/en/guide/toc.yml, src/en/guide/webServices/REST/angularProfile.gdoc
Also fixes https://github.com/grails/grails-doc/issues/409
=> Angular profile documentation

src/en/guide/webServices/REST/angularProfile.gdoc
Documented:
Changes to naming conventions
Ability to change asset folder with config
=> Update Angular profile docs

src/en/guide/security/ssl.gdoc, src/en/guide/toc.yml
Added instructions for using SSL in Development mode. Changes are made for branch 2.5.x as per https://github.com/grails/grails-doc/pull/413#issuecomment-175599053
=> Added ssl in development mode

.gitignore, .project, src/en/guide/gettingStarted/deployingAnApplication.gdoc, src/en/guide/toc.yml, src/en/guide/upgrading/upgrading2x/upgradingGeneral.gdoc, src/en/guide/upgrading/upgrading2x/upgradingPlugins.gdoc
A contribution of additional documentation from my experience of upgrading from Grails 2.4 to 3.x. Help with the pitfalls I encountered, things I wish I had known beforehand and based on questions I have been asked by other developers who are also migrating apps.
Feedback is welcome, I am happy to refine or extend this work.
=> Additional guidance from experience of upgrading from 2.x to 3.x

src/en/guide/services/dependencyInjectionServices.gdoc
This is to document the issue found here:
https://github.com/grails/grails-core/issues/9690
=> documenting grails-core issue 9690

src/en/guide/upgrading.gdoc
Corrected language around the location of the application name in Grails 3.x
=> Grails 3.x upgrade documentation

src/en/guide/theWebLayer/urlmappings/mappingHTTP.gdoc, src/en/ref/Tags/createLink.gdoc, src/en/ref/Tags/link.gdoc
see [grails-core #9191](https://github.com/grails/grails-core/issues/9199) for explanation
=> documented the 'method' argument of g:link and g:createLink

src/en/guide/validation/validationAndInternationalization.gdoc
third time's a charm (here is hoping)
=> added link to an example of a constraint

src/en/guide/async/events/annotations.gdoc
The `@Selector` should be consistent with the other examples.
=> Updated the @Selector to be consistent with the other examples

src/en/guide/commandLine/interactiveMode.gdoc, src/en/guide/i18n/understandingMessageBundles.gdoc, src/en/guide/profiles/creatingProfiles.gdoc, src/en/guide/profiles/profileStructure.gdoc, src/en/guide/testing/functionalTesting.gdoc, src/en/guide/testing/unitTesting/unitTestingControllers.gdoc, src/en/guide/testing/unitTesting/unitTestingDomains.gdoc, src/en/guide/theWebLayer/urlmappings/restfulMappings.gdoc, src/en/guide/webServices/REST/angularProfile.gdoc, src/en/guide/webServices/REST/restProfile.gdoc, src/en/guide/webServices/REST/restfulControllers/generatingRestControllers.gdoc, src/en/guide/webServices/REST/restfulControllers/restControllersStepByStep.gdoc
Fixed some word duplication and a few other typos.
=> Minor cleanup of grammar

src/en/guide/theWebLayer/controllers/commandObjects.gdoc
Improve command object documentation when you want to bind a list of objects. 
Issue https://github.com/grails/grails-doc/issues/487
Reported by @olavgg
=> Improve command object documentation when you want to bind a list of objects. 

src/en/guide/conf/dataSource/multipleDatasources.gdoc
Add note explaining how to inject an additional datasource in a Grails artefact
=> Add note explaining how to inject an additional datasource in a Grails artefact

src/en/guide/theWebLayer/urlmappings.adoc
https://github.com/grails/grails-core/issues/10189#issuecomment-250771908
=> UrlMapping should be inside package

src/en/guide/testing/unitTesting/unitTestingControllers.adoc
Fix response json syntax
Addresses [#10232](https://github.com/grails/grails-core/issues/10232)
=> Fix json docs

src/en/guide/upgrading.adoc
That comma breaks table structure
=> Fix for "Files Not Present" table

src/en/guide/plugins/addingMethodsAtCompileTime.adoc
Related to grails/grails-core#10238
=> Document grails.factories issue

src/en/guide/gettingStarted/requirements.gdoc
Reference: https://github.com/grails/grails-core/issues/10321
=> Add note that Java 9 and later are not supported.

src/en/ref/Domain Classes/createCriteria.adoc
- Note differences in unit tests
- Fix method reference table
=> Cleanup createCriteria page

src/en/guide/conf/environments.adoc, src/en/guide/theWebLayer/taglibs/usingJSPTagLibraries.adoc, src/en/guide/webServices/REST/restProfile.adoc
The doc was using “wound” when it should have been “would”.
=> Correct incorrect word use

src/en/guide/gettingStarted/runningAndDebuggingAnApplication.adoc
Use the -port argument and display new messages from Grails 3.
=> Use Grails 3 syntax and command line output

src/en/guide/testing/unitTesting/unitTestingControllers.adoc
There was a typo (an extra h in http)
=> Fix link to XmlSlurper

src/en/guide/plugins/hookingIntoRuntimeConfiguration.adoc
FilterRegistrationbean has been moved to a different package and previous link was broken
=> Update FilterRegistrationBean API link

src/en/guide/plugins/addingMethodsAtCompileTime.adoc
Added docs for https://github.com/grails/grails-core/issues/10531
=> Updated docs for conditional trait injectors #10531

src/en/guide/conf/dataSource/multipleDatasources.adoc
=> dataSources.dataSource does not work at Grails 3.2.x

src/en/guide/validation/validationAndInternationalization.adoc
Fixes: https://github.com/grails/grails-core/issues/9995
=> Adds Constraints Error Codes table

src/en/guide/theWebLayer/controllers/dataBinding.adoc
Docs for pull https://github.com/grails/grails-core/pull/10666
=> Added docs for BindInitializer

src/en/ref/Database Mapping/column.adoc
Since gorm 6.1  [IdentityEnumType handling changed](http://gorm.grails.org/6.1.x/hibernate/manual/#_identityenumtype_handling_changed) and now enumType can be set to identity
=> Add identity to possible enum types

src/en/guide/plugins/addingMethodsAtCompileTime.adoc
Added MD syntax for the *SomeAnnotation* to make it visually better.
=> Changed MD syntax for class name to make it visually better

src/en/guide/upgrading.adoc
Change chainedTransactionManagerPostProcessor to chainedTransactionManager as defined in:
org.grails.plugins.datasource.DataSourceGrailsPlugin#TRANSACTION_MANAGER_ENABLED = 'grails.transaction.chainedTransactionManager.enabled'
=> Correct chainedTransactionManagerPostProcessor to chainedTransactionManager

src/en/guide/commandLine/creatingCustomCommands.adoc
https://stackoverflow.com/questions/45485947/how-do-i-use-grailsapplicationcommand-with-the-gradle-wrapper-in-an-angular-proj
=> Updated docs to show correct usage of runCommand

src/en/guide/theWebLayer/urlmappings/restfulMappings.adoc
This is based on the issue [#10712]( https://github.com/grails/grails-core/issues/10712). Please suggest if more details should be added to the documentation.
=> Minor corrections in Url mappings doc

src/en/guide/theWebLayer/controllers/modelsAndViews.adoc
I think it should be, (by following the preceeding example) numberCrunch . No ?
=> is the view name accounting correct ?

src/en/guide/commandLine/gradleBuild/gradlePlugins.adoc
Looks like an extra end bracket was added accidentally.
=> Noticed and extra end bracket "]" on line 14

src/en/ref/Controllers/redirect.adoc
Updated documentation explaining behavior for partial URI redirects. This needs to be merged with grails/grails-core#10910
=> Allow generation of partial URIs for redirect

src/en/guide/gettingStarted/ide.adoc
=> Updated IntelliJ IDEA instructions

src/en/guide/conf/config/ymlOptions.adoc
Added section on external configuration
=> Added section on external configuration

src/en/guide/commandLine.adoc
Added docs about grails commandline arguments
=> Added docs about grails commandline arguments

src/en/guide/toc.yml
=> Typo in interceptors

src/en/guide/conf/dataSource.adoc
This PR needs to be merged after https://github.com/grails/grails-data-mapping/pull/1168
=> Document how to define the db connetion pool class

src/en/guide/conf/dataSource/multipleDatasources.adoc
=> Duplicated words

src/en/guide/index.adoc, src/en/guide/toc.yml
=> Fix typo 'Inteceptors'

src/en/guide/theWebLayer/controllers/jsonResponses.adoc
=> Fix typo 'capible'

src/en/guide/gettingStarted/conventionOverConfiguration.adoc
Scripts are now located in src/main/scripts
=> Add new path for scripts

src/en/guide/gettingStarted/aHelloWorldExample.adoc
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#servlet-specific-server-properties
server.context-path -> server.servlet.context-path
=> Grails 4 configuration changes.

src/en/guide/gettingStarted/conventionOverConfiguration.adoc
Added M in MVC to domain reference
=> Added missing M in MVC

src/en/guide/conf/config/logging/maskingRequestParametersFromStacktraceLogs.adoc
Doc currently refers to .yaml and it should be .yml
=> Incorrect file extension

src/en/guide/conf/dataSource/multipleDatasources.adoc
Added an application.groovy example for multiple dataSources.
=> Add an application.groovy example for dataSources

src/en/ref/Controllers/respond.adoc
* Updated information on how to augment the model.
* view and model are also supported for JSON views.
=> grails/grails-core#10997 Updated respond.adoc

src/en/guide/theWebLayer/controllers/dataBinding.adoc
Updated guide on how to handle prioritize custom value converter when there is more than one converter of the same type.
=>  grails/grails-core#9831  Updated dataBinding.adoc

src/en/guide/theWebLayer/contentNegotiation.adoc
Fixes issue https://github.com/grails/grails-core/issues/10765#issuecomment-320323385
=> Content negotiation update

src/en/guide/conf/config/logging.adoc
This part is written as if Grails 3 were the current version.
=> Minor wording improvement

src/en/guide/conf/environments.adoc
+ Indent correctly the `properties` section of `dataSource` section.
+ Add the missing transcoding in groovy.
=> Correct indentation and groovy language

src/en/guide/plugins/creatingAndInstallingPlugins.adoc
Include instruction to add `mavenLocal()` to repository list.
=> Add `mavenLocal()` to repository list.

src/en/guide/gettingStarted/ide.adoc
Took the opportunity to format the file a bit.
=> Added link to a VSCode extension

src/en/guide/upgrading/upgrading40x.adoc
- Added notes for GORM MongoDB Driver changes
=> Update Upgrading from Grails 4.0.x

src/en/guide/gettingStarted/requirements.adoc
=> Simple change

src/en/guide/testing/integrationTesting.adoc
this was my understanding in better sentence
=> Update explanation of setUpData method in integration test

src/en/guide/commandLine/gradleBuild/gradleTasks.adoc
test-app invokes check gradle method, gradle test only runs the unit tests
=> grails test-app / gradle mapping fixed

src/en/guide/introduction/whatsNew/dependencyUpgrades.adoc
=> version placeholder. Backport from #781

src/en/guide/testing.adoc
Small correction to the documentation
=> Fix test report directories in testing.adoc

src/en/guide/upgrading/upgrading40x.adoc
Update 4.1->5.0 in three different places.
=> Change documented version from 4.1 to 5.0

build.gradle, gradle.properties
Spring Boot 2.5.6
Spring 5.3.13
GORM 7.1.0
Groovy 3.0.7
=> Updated Dependencies

src/en/guide/REST/restfulControllers/extendingRestfulController.adoc
Minor grammatical correction s/it’s/its/
=> Minor grammatical correction s/it’s/its/

src/en/guide/upgrading/upgrading40x.adoc
grailsVersion=5.2.0 instead of grailsVersion=5.1.1
Add information about update Gradle version in Grails 5.
=> Update Grails version & add Gradle 7.2

src/en/ref/Domain Classes/createCriteria.adoc
=> Added inList as criteria method.

src/en/guide/plugins/creatingAndInstallingPlugins.adoc, src/en/guide/spring/propertyPlaceholderConfiguration.adoc, src/en/guide/spring/springdslAdditional.adoc
=> Changed some usages of deprecated dot config notation

src/en/guide/theWebLayer/urlmappings/mappingToResponseCodes.adoc
Related PRs:
- https://github.com/grails/grails-core/pull/13309
- https://github.com/grails/grails-core/pull/13310
=> Implement URI-based response code URL mappings

src/en/ref/Command Line/create-job.adoc
- Related PR: https://github.com/grails/grails-forge/pull/276
=> Document new CLI command "create-job"

build.gradle, src/en/guide/REST/restProfile.adoc, src/en/guide/gettingStarted/aHelloWorldExample.adoc, src/en/guide/gettingStarted/conventionOverConfiguration.adoc, src/en/guide/gettingStarted/creatingAnApplication.adoc, src/en/guide/gettingStarted/creatingArtefacts.adoc, src/en/guide/gettingStarted/deployingAnApplication.adoc, src/en/guide/gettingStarted/downloadingAndInstalling.adoc, src/en/guide/gettingStarted/generatingAnApplication.adoc, src/en/guide/gettingStarted/ide.adoc, src/en/guide/gettingStarted/runningAndDebuggingAnApplication.adoc, src/en/guide/gettingStarted/supportedJavaEEContainers.adoc, src/en/guide/gettingStarted/testingAnApplication.adoc, src/en/guide/gettingStarted/usingInteractiveMode.adoc, src/en/guide/theWebLayer/urlmappings/mappingToResponseCodes.adoc, src/en/ref/Command Line/bootRun.adoc, src/en/ref/Command Line/create-app.adoc, src/en/ref/Command Line/create-restapi.adoc, src/en/ref/Command Line/install-templates.adoc, src/en/ref/Command Line/schema-export.adoc
Focused on the getting started section but also some updates elsewhere.
=> fix(docs): Update documentation

build.gradle, src/en/ref/Database Mapping/id.adoc
- Remove `uuid.hex` generator
- Add `uuid2` generator
- Fix some links
- Remove `source` from groovy code blocks that are not complete classes
=> fix(docs): Update id.adoc

build.gradle
Update PublishGudie task to set correct targetDir
=> fix(build): update build configurations

.github/workflows/gradle.yml, build.gradle, gradle.properties
- Update Javase reference link to point to version 17
- Update api docs directory to build/docs/api in grails-core and add a note regarding the change
- Change githubBranch to 7.0.x
- Update grailsVersion
- Modify Java CI workflow to skip snapshot for 7.0.x branch
=> chore: Update project configurations and workflows
